---
- name: OCP Homework assessment - Bastion tasks
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Git repo clone 
      git:
        repo: https://github.com/steven-outteridge/RedHat-OCP-Homework.git
        dest: /root/RedHat-OCP-Homework
      tags:
        - git





#    - name: LOCALHOST BASTION ONLY Check atomic-openshift-clients openshift-ansible are installed to latest version
 #     connection: local
   #   yum:
    #    name: atomic-openshift-clients
     #   state: present
#        name: atomic-openshift-clients, openshift-ansible
