#Preinstall checks:
#Changes and GUID in hosts file to the correct hoist name variable
#Checks that the bastion host has the latest "atomic-openshift-clients" & "openshift-ansible" packages install
---
- name: OCP Homework assessment - Bastion tasks
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: LOCALHOST BASTION ONLY Check atomic-openshift-clients openshift-ansible are installed to latest version
      yum:
        name: atomic-openshift-clients, openshift-ansible
        state: latest
    - name: Generate Inventory Hosts File
      script: /root/RedHat-OCP-Homework/scripts/generate-guid-hosts.sh
