---
- name: OCP Homework assessment - Post install checks
  hosts: OSEv3

  tasks:
    - name:   MASTER Copy.kube dir from master to Bastion
      when: inventory_hostname in groups['masters']
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/config
        flat: yes
