---
- name: OCP Homework assessment - CICD Pipeline deployment
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: run the script to deploy the apps and pipeline
      script: /root/RedHat-OCP-Homework/Jenkins/cicd-create.sh
